<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CmsCashaccountDetailsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cms_cashaccount_details')->insert([
            [
                'Journal'         => 'CA',
                'BranchID'        => 'RC001',
                'CashAccount'     => '100001',
                'CashAccountDesc' => 'BDO CHECKING ACCOUNT',
                'Credit'          => 0.00,
                'Debit'           => 250000.00,
                'Amount'          => 250000.00,
                'DocumentRef'     => 'CA000001',
                'PostPeriod'      => '08-2026',
                'Module'          => 'CA',
                'ReferenceNumber' => 'REF000001',
                'Type'            => 'RECEIPT',
                'Posted'          => 'true',
                'Released'        => 'true',
                'Status'          => 'Posted',
                'TransactionDate' => Carbon::now()->subDays(1)->format('Y-m-d'),
                'Company'         => 'ROPALI CORPORATION',
                'CreatedAt'       => Carbon::now()->subDays(1)->format('Y-m-d H:i:s'),
            ],
            [
                'Journal'         => 'CA',
                'BranchID'        => 'RC002',
                'CashAccount'     => '100002',
                'CashAccountDesc' => 'BPI SAVINGS ACCOUNT',
                'Credit'          => 150000.00,
                'Debit'           => 0.00,
                'Amount'          => 150000.00,
                'DocumentRef'     => 'CA000002',
                'PostPeriod'      => '08-2026',
                'Module'          => 'CA',
                'ReferenceNumber' => 'REF000002',
                'Type'            => 'DISBURSEMENT',
                'Posted'          => 'true',
                'Released'        => 'true',
                'Status'          => 'Posted',
                'TransactionDate' => Carbon::now()->subDays(2)->format('Y-m-d'),
                'Company'         => 'ROPALI CORPORATION',
                'CreatedAt'       => Carbon::now()->subDays(2)->format('Y-m-d H:i:s'),
            ],
            [
                'Journal'         => 'CA',
                'BranchID'        => 'RC003',
                'CashAccount'     => '100003',
                'CashAccountDesc' => 'METROBANK CURRENT ACCOUNT',
                'Credit'          => 0.00,
                'Debit'           => 500000.00,
                'Amount'          => 500000.00,
                'DocumentRef'     => 'CA000003',
                'PostPeriod'      => '08-2026',
                'Module'          => 'CA',
                'ReferenceNumber' => 'REF000003',
                'Type'            => 'RECEIPT',
                'Posted'          => 'true',
                'Released'        => 'true',
                'Status'          => 'Posted',
                'TransactionDate' => Carbon::now()->subDays(3)->format('Y-m-d'),
                'Company'         => 'ROPALI CORPORATION',
                'CreatedAt'       => Carbon::now()->subDays(3)->format('Y-m-d H:i:s'),
            ],
            [
                'Journal'         => 'CA',
                'BranchID'        => 'MB001',
                'CashAccount'     => '100004',
                'CashAccountDesc' => 'LANDBANK CHECKING ACCOUNT',
                'Credit'          => 75000.00,
                'Debit'           => 0.00,
                'Amount'          => 75000.00,
                'DocumentRef'     => 'CA000004',
                'PostPeriod'      => '08-2026',
                'Module'          => 'CA',
                'ReferenceNumber' => 'REF000004',
                'Type'            => 'DISBURSEMENT',
                'Posted'          => 'true',
                'Released'        => 'true',
                'Status'          => 'Posted',
                'TransactionDate' => Carbon::now()->subDays(4)->format('Y-m-d'),
                'Company'         => 'MOTORBELLE CORPORATION',
                'CreatedAt'       => Carbon::now()->subDays(4)->format('Y-m-d H:i:s'),
            ],
            [
                'Journal'         => 'CA',
                'BranchID'        => 'MB002',
                'CashAccount'     => '100005',
                'CashAccountDesc' => 'RCBC CURRENT ACCOUNT',
                'Credit'          => 0.00,
                'Debit'           => 320000.00,
                'Amount'          => 320000.00,
                'DocumentRef'     => 'CA000005',
                'PostPeriod'      => '08-2026',
                'Module'          => 'CA',
                'ReferenceNumber' => 'REF000005',
                'Type'            => 'RECEIPT',
                'Posted'          => 'true',
                'Released'        => 'true',
                'Status'          => 'Posted',
                'TransactionDate' => Carbon::now()->subDays(5)->format('Y-m-d'),
                'Company'         => 'MOTORBELLE CORPORATION',
                'CreatedAt'       => Carbon::now()->subDays(5)->format('Y-m-d H:i:s'),
            ],
            [
                'Journal'         => 'CA',
                'BranchID'        => 'MA001',
                'CashAccount'     => '100006',
                'CashAccountDesc' => 'PNB SAVINGS ACCOUNT',
                'Credit'          => 200000.00,
                'Debit'           => 0.00,
                'Amount'          => 200000.00,
                'DocumentRef'     => 'CA000006',
                'PostPeriod'      => '08-2026',
                'Module'          => 'CA',
                'ReferenceNumber' => 'REF000006',
                'Type'            => 'DISBURSEMENT',
                'Posted'          => 'true',
                'Released'        => 'true',
                'Status'          => 'Posted',
                'TransactionDate' => Carbon::now()->subDays(8)->format('Y-m-d'),
                'Company'         => 'MOTORALI CORPORATION',
                'CreatedAt'       => Carbon::now()->subDays(8)->format('Y-m-d H:i:s'),
            ],
            [
                'Journal'         => 'CA',
                'BranchID'        => 'MA002',
                'CashAccount'     => '100007',
                'CashAccountDesc' => 'UNIONBANK CHECKING ACCOUNT',
                'Credit'          => 0.00,
                'Debit'           => 450000.00,
                'Amount'          => 450000.00,
                'DocumentRef'     => 'CA000007',
                'PostPeriod'      => '08-2026',
                'Module'          => 'CA',
                'ReferenceNumber' => 'REF000007',
                'Type'            => 'RECEIPT',
                'Posted'          => 'true',
                'Released'        => 'true',
                'Status'          => 'Posted',
                'TransactionDate' => Carbon::now()->subDays(9)->format('Y-m-d'),
                'Company'         => 'MOTORALI CORPORATION',
                'CreatedAt'       => Carbon::now()->subDays(9)->format('Y-m-d H:i:s'),
            ],
            [
                'Journal'         => 'CA',
                'BranchID'        => 'MO001',
                'CashAccount'     => '100008',
                'CashAccountDesc' => 'CHINABANK CURRENT ACCOUNT',
                'Credit'          => 180000.00,
                'Debit'           => 0.00,
                'Amount'          => 180000.00,
                'DocumentRef'     => 'CA000008',
                'PostPeriod'      => '08-2026',
                'Module'          => 'CA',
                'ReferenceNumber' => 'REF000008',
                'Type'            => 'DISBURSEMENT',
                'Posted'          => 'true',
                'Released'        => 'true',
                'Status'          => 'Posted',
                'TransactionDate' => Carbon::now()->subDays(10)->format('Y-m-d'),
                'Company'         => 'MOTOROBEE CORPORATION',
                'CreatedAt'       => Carbon::now()->subDays(10)->format('Y-m-d H:i:s'),
            ],
            [
                'Journal'         => 'CA',
                'BranchID'        => 'MO002',
                'CashAccount'     => '100009',
                'CashAccountDesc' => 'SECURITY BANK SAVINGS ACCOUNT',
                'Credit'          => 0.00,
                'Debit'           => 670000.00,
                'Amount'          => 670000.00,
                'DocumentRef'     => 'CA000009',
                'PostPeriod'      => '08-2026',
                'Module'          => 'CA',
                'ReferenceNumber' => 'REF000009',
                'Type'            => 'RECEIPT',
                'Posted'          => 'true',
                'Released'        => 'true',
                'Status'          => 'Posted',
                'TransactionDate' => Carbon::now()->subDays(11)->format('Y-m-d'),
                'Company'         => 'MOTOROBEE CORPORATION',
                'CreatedAt'       => Carbon::now()->subDays(11)->format('Y-m-d H:i:s'),
            ],
            [
                'Journal'         => 'CA',
                'BranchID'        => 'MO003',
                'CashAccount'     => '100010',
                'CashAccountDesc' => 'EASTWEST CHECKING ACCOUNT',
                'Credit'          => 90000.00,
                'Debit'           => 0.00,
                'Amount'          => 90000.00,
                'DocumentRef'     => 'CA000010',
                'PostPeriod'      => '08-2026',
                'Module'          => 'CA',
                'ReferenceNumber' => 'REF000010',
                'Type'            => 'DISBURSEMENT',
                'Posted'          => 'true',
                'Released'        => 'true',
                'Status'          => 'Posted',
                'TransactionDate' => Carbon::now()->subDays(12)->format('Y-m-d'),
                'Company'         => 'MOTOROBEE CORPORATION',
                'CreatedAt'       => Carbon::now()->subDays(12)->format('Y-m-d H:i:s'),
            ],
        ]);
    }
}
