<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CmsFundVoucherSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cms_fund_voucher')->insert([
            [
                'TransferNbr'   => 'FV-2026-0001',
                'BatchNbr'      => 'B-2026-0001',
                'BatchDate'     => Carbon::now()->subDays(10)->format('Y-m-d'),
                'BatchFinPeriod'=> '08-2026',
                'Branch'        => 'RC001',
                'CashAccount'   => '100001',
                'Account'       => '1010',
                'Particulars'   => 'FUND TRANSFER TO OPERATIONS',
                'Debit'         => 500000.00,
                'Credit'        => 0.00,
                'Company'       => 'ROPALI CORPORATION',
                'Currency'      => 'PHP',
                'LineNbr'       => 1,
                'TotalDebit'    => 500000.00,
                'TotalCredit'   => 0.00,
                            ],
            [
                'TransferNbr'   => 'FV-2026-0001',
                'BatchNbr'      => 'B-2026-0001',
                'BatchDate'     => Carbon::now()->subDays(10)->format('Y-m-d'),
                'BatchFinPeriod'=> '08-2026',
                'Branch'        => 'RC001',
                'CashAccount'   => '100002',
                'Account'       => '1020',
                'Particulars'   => 'FUND TRANSFER TO OPERATIONS - OFFSET',
                'Debit'         => 0.00,
                'Credit'        => 500000.00,
                'Company'       => 'ROPALI CORPORATION',
                'Currency'      => 'PHP',
                'LineNbr'       => 2,
                'TotalDebit'    => 0.00,
                'TotalCredit'   => 500000.00,
                            ],
            [
                'TransferNbr'   => 'FV-2026-0002',
                'BatchNbr'      => 'B-2026-0002',
                'BatchDate'     => Carbon::now()->subDays(8)->format('Y-m-d'),
                'BatchFinPeriod'=> '08-2026',
                'Branch'        => 'MB001',
                'CashAccount'   => '100003',
                'Account'       => '1010',
                'Particulars'   => 'INTERCOMPANY FUND TRANSFER',
                'Debit'         => 750000.00,
                'Credit'        => 0.00,
                'Company'       => 'MOTORBELLE CORPORATION',
                'Currency'      => 'PHP',
                'LineNbr'       => 1,
                'TotalDebit'    => 750000.00,
                'TotalCredit'   => 0.00,
                            ],
            [
                'TransferNbr'   => 'FV-2026-0002',
                'BatchNbr'      => 'B-2026-0002',
                'BatchDate'     => Carbon::now()->subDays(8)->format('Y-m-d'),
                'BatchFinPeriod'=> '08-2026',
                'Branch'        => 'MB001',
                'CashAccount'   => '100004',
                'Account'       => '2010',
                'Particulars'   => 'INTERCOMPANY FUND TRANSFER - OFFSET',
                'Debit'         => 0.00,
                'Credit'        => 750000.00,
                'Company'       => 'MOTORBELLE CORPORATION',
                'Currency'      => 'PHP',
                'LineNbr'       => 2,
                'TotalDebit'    => 0.00,
                'TotalCredit'   => 750000.00,
                            ],
            [
                'TransferNbr'   => 'FV-2026-0003',
                'BatchNbr'      => 'B-2026-0003',
                'BatchDate'     => Carbon::now()->subDays(6)->format('Y-m-d'),
                'BatchFinPeriod'=> '08-2026',
                'Branch'        => 'MA001',
                'CashAccount'   => '100005',
                'Account'       => '1010',
                'Particulars'   => 'SALARY FUND TRANSFER',
                'Debit'         => 1200000.00,
                'Credit'        => 0.00,
                'Company'       => 'MOTORALI CORPORATION',
                'Currency'      => 'PHP',
                'LineNbr'       => 1,
                'TotalDebit'    => 1200000.00,
                'TotalCredit'   => 0.00,
                            ],
            [
                'TransferNbr'   => 'FV-2026-0003',
                'BatchNbr'      => 'B-2026-0003',
                'BatchDate'     => Carbon::now()->subDays(6)->format('Y-m-d'),
                'BatchFinPeriod'=> '08-2026',
                'Branch'        => 'MA001',
                'CashAccount'   => '100006',
                'Account'       => '5010',
                'Particulars'   => 'SALARY FUND TRANSFER - SALARIES EXPENSE',
                'Debit'         => 0.00,
                'Credit'        => 1200000.00,
                'Company'       => 'MOTORALI CORPORATION',
                'Currency'      => 'PHP',
                'LineNbr'       => 2,
                'TotalDebit'    => 0.00,
                'TotalCredit'   => 1200000.00,
                            ],
            [
                'TransferNbr'   => 'FV-2026-0004',
                'BatchNbr'      => 'B-2026-0004',
                'BatchDate'     => Carbon::now()->subDays(4)->format('Y-m-d'),
                'BatchFinPeriod'=> '08-2026',
                'Branch'        => 'MO001',
                'CashAccount'   => '100007',
                'Account'       => '1010',
                'Particulars'   => 'CAPITAL EXPENDITURE TRANSFER',
                'Debit'         => 2500000.00,
                'Credit'        => 0.00,
                'Company'       => 'MOTOROBEE CORPORATION',
                'Currency'      => 'PHP',
                'LineNbr'       => 1,
                'TotalDebit'    => 2500000.00,
                'TotalCredit'   => 0.00,
                            ],
            [
                'TransferNbr'   => 'FV-2026-0004',
                'BatchNbr'      => 'B-2026-0004',
                'BatchDate'     => Carbon::now()->subDays(4)->format('Y-m-d'),
                'BatchFinPeriod'=> '08-2026',
                'Branch'        => 'MO001',
                'CashAccount'   => '100008',
                'Account'       => '1500',
                'Particulars'   => 'CAPITAL EXPENDITURE TRANSFER - FIXED ASSETS',
                'Debit'         => 0.00,
                'Credit'        => 2500000.00,
                'Company'       => 'MOTOROBEE CORPORATION',
                'Currency'      => 'PHP',
                'LineNbr'       => 2,
                'TotalDebit'    => 0.00,
                'TotalCredit'   => 2500000.00,
                            ],
            [
                'TransferNbr'   => 'FV-2026-0005',
                'BatchNbr'      => 'B-2026-0005',
                'BatchDate'     => Carbon::now()->subDays(2)->format('Y-m-d'),
                'BatchFinPeriod'=> '08-2026',
                'Branch'        => 'RC002',
                'CashAccount'   => '100009',
                'Account'       => '1010',
                'Particulars'   => 'UTILITY PAYMENT TRANSFER',
                'Debit'         => 85000.00,
                'Credit'        => 0.00,
                'Company'       => 'ROPALI CORPORATION',
                'Currency'      => 'PHP',
                'LineNbr'       => 1,
                'TotalDebit'    => 85000.00,
                'TotalCredit'   => 0.00,
                            ],
            [
                'TransferNbr'   => 'FV-2026-0005',
                'BatchNbr'      => 'B-2026-0005',
                'BatchDate'     => Carbon::now()->subDays(2)->format('Y-m-d'),
                'BatchFinPeriod'=> '08-2026',
                'Branch'        => 'RC002',
                'CashAccount'   => '100010',
                'Account'       => '6010',
                'Particulars'   => 'UTILITY PAYMENT TRANSFER - UTILITIES EXPENSE',
                'Debit'         => 0.00,
                'Credit'        => 85000.00,
                'Company'       => 'ROPALI CORPORATION',
                'Currency'      => 'PHP',
                'LineNbr'       => 2,
                'TotalDebit'    => 0.00,
                'TotalCredit'   => 85000.00,
                            ],
        ]);
    }
}
