<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CmsMultipleReconSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cms_multiple_recon')->insert([
            [
                'MultipleID'   => 'MR-2026-0001',
                'CreatedBy'    => 'admin@fundsync.com',
                'BankRef'      => 'BANKREF001',
                'AcumaticaRef' => 'ACUREF001',
                'Company'      => 'ROPALI CORPORATION',
                'Amount'       => 250000.00,
                'Remaining'    => 0.00,
                'Remain'       => 0.00,
                'Type'         => 'DEBIT',
                'Status'       => 1,
                'CreatedAt'    => Carbon::now()->subDays(10)->format('Y-m-d H:i:s'),
            ],
            [
                'MultipleID'   => 'MR-2026-0001',
                'CreatedBy'    => 'admin@fundsync.com',
                'BankRef'      => 'BANKREF002',
                'AcumaticaRef' => 'ACUREF002',
                'Company'      => 'ROPALI CORPORATION',
                'Amount'       => 100000.00,
                'Remaining'    => 0.00,
                'Remain'       => 0.00,
                'Type'         => 'CREDIT',
                'Status'       => 1,
                'CreatedAt'    => Carbon::now()->subDays(10)->format('Y-m-d H:i:s'),
            ],
            [
                'MultipleID'   => 'MR-2026-0002',
                'CreatedBy'    => 'admin@fundsync.com',
                'BankRef'      => 'BANKREF003',
                'AcumaticaRef' => 'ACUREF003',
                'Company'      => 'MOTORBELLE CORPORATION',
                'Amount'       => 375000.00,
                'Remaining'    => 125000.00,
                'Remain'       => 125000.00,
                'Type'         => 'DEBIT',
                'Status'       => null,
                'CreatedAt'    => Carbon::now()->subDays(8)->format('Y-m-d H:i:s'),
            ],
            [
                'MultipleID'   => 'MR-2026-0002',
                'CreatedBy'    => 'admin@fundsync.com',
                'BankRef'      => 'BANKREF004',
                'AcumaticaRef' => 'ACUREF004',
                'Company'      => 'MOTORBELLE CORPORATION',
                'Amount'       => 200000.00,
                'Remaining'    => 50000.00,
                'Remain'       => 50000.00,
                'Type'         => 'CREDIT',
                'Status'       => null,
                'CreatedAt'    => Carbon::now()->subDays(8)->format('Y-m-d H:i:s'),
            ],
            [
                'MultipleID'   => 'MR-2026-0003',
                'CreatedBy'    => 'admin@fundsync.com',
                'BankRef'      => 'BANKREF005',
                'AcumaticaRef' => 'ACUREF005',
                'Company'      => 'MOTORALI CORPORATION',
                'Amount'       => 500000.00,
                'Remaining'    => 0.00,
                'Remain'       => 0.00,
                'Type'         => 'DEBIT',
                'Status'       => 1,
                'CreatedAt'    => Carbon::now()->subDays(6)->format('Y-m-d H:i:s'),
            ],
            [
                'MultipleID'   => 'MR-2026-0003',
                'CreatedBy'    => 'admin@fundsync.com',
                'BankRef'      => 'BANKREF006',
                'AcumaticaRef' => 'ACUREF006',
                'Company'      => 'MOTORALI CORPORATION',
                'Amount'       => 75000.00,
                'Remaining'    => 0.00,
                'Remain'       => 0.00,
                'Type'         => 'CREDIT',
                'Status'       => 1,
                'CreatedAt'    => Carbon::now()->subDays(6)->format('Y-m-d H:i:s'),
            ],
            [
                'MultipleID'   => 'MR-2026-0004',
                'CreatedBy'    => 'admin@fundsync.com',
                'BankRef'      => 'BANKREF007',
                'AcumaticaRef' => 'ACUREF007',
                'Company'      => 'MOTOROBEE CORPORATION',
                'Amount'       => 420000.00,
                'Remaining'    => 170000.00,
                'Remain'       => 170000.00,
                'Type'         => 'DEBIT',
                'Status'       => null,
                'CreatedAt'    => Carbon::now()->subDays(4)->format('Y-m-d H:i:s'),
            ],
            [
                'MultipleID'   => 'MR-2026-0004',
                'CreatedBy'    => 'admin@fundsync.com',
                'BankRef'      => 'BANKREF008',
                'AcumaticaRef' => 'ACUREF008',
                'Company'      => 'MOTOROBEE CORPORATION',
                'Amount'       => 50000.00,
                'Remaining'    => 0.00,
                'Remain'       => 0.00,
                'Type'         => 'CREDIT',
                'Status'       => 1,
                'CreatedAt'    => Carbon::now()->subDays(4)->format('Y-m-d H:i:s'),
            ],
            [
                'MultipleID'   => 'MR-2026-0005',
                'CreatedBy'    => 'admin@fundsync.com',
                'BankRef'      => 'BANKREF009',
                'AcumaticaRef' => 'ACUREF009',
                'Company'      => 'ROPALI CORPORATION',
                'Amount'       => 300000.00,
                'Remaining'    => 0.00,
                'Remain'       => 0.00,
                'Type'         => 'DEBIT',
                'Status'       => 1,
                'CreatedAt'    => Carbon::now()->subDays(2)->format('Y-m-d H:i:s'),
            ],
            [
                'MultipleID'   => 'MR-2026-0005',
                'CreatedBy'    => 'admin@fundsync.com',
                'BankRef'      => 'BANKREF010',
                'AcumaticaRef' => 'ACUREF010',
                'Company'      => 'ROPALI CORPORATION',
                'Amount'       => 150000.00,
                'Remaining'    => 0.00,
                'Remain'       => 0.00,
                'Type'         => 'CREDIT',
                'Status'       => 1,
                'CreatedAt'    => Carbon::now()->subDays(2)->format('Y-m-d H:i:s'),
            ],
        ]);
    }
}
