<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CmsVoucherDetailsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cms_voucher_details')->insert([
            [
                'Vendor'       => 'V000001',
                'VendorName'   => 'MERALCO - MANILA ELECTRIC COMPANY',
                'ReferenceNbr' => 'PV-2026-0001',
                'PostDate'     => Carbon::now()->subDays(10)->format('Y-m-d'),
                'Currency'     => 'PHP',
                'CheckNo'      => 'CHK000001',
                'APAccount'    => '2000',
                'APPayment'    => 25000.00,
                'CHAccount'    => '1100',
                'CHPayment'    => 25000.00,
                'BLAmount'     => 25000.00,
                'Purpose'      => 'PAYMENT FOR ELECTRICITY BILL - JULY 2026',
                'Name'         => 'MANILA ELECTRIC COMPANY',
                'Company'      => 'ROPALI CORPORATION',
                'Type'         => 'CHECK',
                'Total'        => 25000.00,
                'IsPrint'      => 0,
                            ],
            [
                'Vendor'       => 'V000002',
                'VendorName'   => 'SMART COMMUNICATIONS INC.',
                'ReferenceNbr' => 'PV-2026-0002',
                'PostDate'     => Carbon::now()->subDays(9)->format('Y-m-d'),
                'Currency'     => 'PHP',
                'CheckNo'      => 'CHK000002',
                'APAccount'    => '2000',
                'APPayment'    => 8500.00,
                'CHAccount'    => '1100',
                'CHPayment'    => 8500.00,
                'BLAmount'     => 8500.00,
                'Purpose'      => 'PAYMENT FOR TELECOMMUNICATIONS BILL',
                'Name'         => 'SMART COMMUNICATIONS INC.',
                'Company'      => 'ROPALI CORPORATION',
                'Type'         => 'ONLINE',
                'Total'        => 8500.00,
                'IsPrint'      => 0,
                            ],
            [
                'Vendor'       => 'V000003',
                'VendorName'   => 'INTERNATIONAL CONTAINER TERMINAL SERVICES',
                'ReferenceNbr' => 'PV-2026-0003',
                'PostDate'     => Carbon::now()->subDays(8)->format('Y-m-d'),
                'Currency'     => 'PHP',
                'CheckNo'      => 'CHK000003',
                'APAccount'    => '2000',
                'APPayment'    => 150000.00,
                'CHAccount'    => '1100',
                'CHPayment'    => 150000.00,
                'BLAmount'     => 150000.00,
                'Purpose'      => 'PAYMENT FOR PORT HANDLING FEES',
                'Name'         => 'INTERNATIONAL CONTAINER TERMINAL SERVICES',
                'Company'      => 'MOTORBELLE CORPORATION',
                'Type'         => 'CHECK',
                'Total'        => 150000.00,
                'IsPrint'      => 0,
                            ],
            [
                'Vendor'       => 'V000004',
                'VendorName'   => 'NATIONAL BOOKSTORE INC.',
                'ReferenceNbr' => 'PV-2026-0004',
                'PostDate'     => Carbon::now()->subDays(7)->format('Y-m-d'),
                'Currency'     => 'PHP',
                'CheckNo'      => 'CHK000004',
                'APAccount'    => '2000',
                'APPayment'    => 12500.00,
                'CHAccount'    => '1100',
                'CHPayment'    => 12500.00,
                'BLAmount'     => 12500.00,
                'Purpose'      => 'PAYMENT FOR OFFICE SUPPLIES',
                'Name'         => 'NATIONAL BOOKSTORE INC.',
                'Company'      => 'MOTORBELLE CORPORATION',
                'Type'         => 'CHECK',
                'Total'        => 12500.00,
                'IsPrint'      => 0,
                            ],
            [
                'Vendor'       => 'V000005',
                'VendorName'   => 'GLOBE TELECOM INC.',
                'ReferenceNbr' => 'PV-2026-0005',
                'PostDate'     => Carbon::now()->subDays(6)->format('Y-m-d'),
                'Currency'     => 'PHP',
                'CheckNo'      => 'CHK000005',
                'APAccount'    => '2000',
                'APPayment'    => 7200.00,
                'CHAccount'    => '1100',
                'CHPayment'    => 7200.00,
                'BLAmount'     => 7200.00,
                'Purpose'      => 'PAYMENT FOR INTERNET SUBSCRIPTION',
                'Name'         => 'GLOBE TELECOM INC.',
                'Company'      => 'MOTORALI CORPORATION',
                'Type'         => 'ONLINE',
                'Total'        => 7200.00,
                'IsPrint'      => 0,
                            ],
            [
                'Vendor'       => 'V000006',
                'VendorName'   => 'AYALA PROPERTY MANAGEMENT CORP.',
                'ReferenceNbr' => 'PV-2026-0006',
                'PostDate'     => Carbon::now()->subDays(5)->format('Y-m-d'),
                'Currency'     => 'PHP',
                'CheckNo'      => 'CHK000006',
                'APAccount'    => '2000',
                'APPayment'    => 85000.00,
                'CHAccount'    => '1100',
                'CHPayment'    => 85000.00,
                'BLAmount'     => 85000.00,
                'Purpose'      => 'PAYMENT FOR OFFICE RENTAL - AUGUST 2026',
                'Name'         => 'AYALA PROPERTY MANAGEMENT CORP.',
                'Company'      => 'MOTORALI CORPORATION',
                'Type'         => 'CHECK',
                'Total'        => 85000.00,
                'IsPrint'      => 0,
                            ],
            [
                'Vendor'       => 'V000007',
                'VendorName'   => 'FIRST PHILIPPINE HOLDINGS CORP.',
                'ReferenceNbr' => 'PV-2026-0007',
                'PostDate'     => Carbon::now()->subDays(4)->format('Y-m-d'),
                'Currency'     => 'PHP',
                'CheckNo'      => 'CHK000007',
                'APAccount'    => '2000',
                'APPayment'    => 320000.00,
                'CHAccount'    => '1100',
                'CHPayment'    => 320000.00,
                'BLAmount'     => 320000.00,
                'Purpose'      => 'PAYMENT FOR FUEL AND OIL SUPPLIES',
                'Name'         => 'FIRST PHILIPPINE HOLDINGS CORP.',
                'Company'      => 'MOTOROBEE CORPORATION',
                'Type'         => 'CHECK',
                'Total'        => 320000.00,
                'IsPrint'      => 0,
                            ],
            [
                'Vendor'       => 'V000008',
                'VendorName'   => 'MANILA WATER COMPANY INC.',
                'ReferenceNbr' => 'PV-2026-0008',
                'PostDate'     => Carbon::now()->subDays(3)->format('Y-m-d'),
                'Currency'     => 'PHP',
                'CheckNo'      => 'CHK000008',
                'APAccount'    => '2000',
                'APPayment'    => 4800.00,
                'CHAccount'    => '1100',
                'CHPayment'    => 4800.00,
                'BLAmount'     => 4800.00,
                'Purpose'      => 'PAYMENT FOR WATER BILL - JULY 2026',
                'Name'         => 'MANILA WATER COMPANY INC.',
                'Company'      => 'MOTOROBEE CORPORATION',
                'Type'         => 'ONLINE',
                'Total'        => 4800.00,
                'IsPrint'      => 0,
                            ],
            [
                'Vendor'       => 'V000009',
                'VendorName'   => 'SM PRIME HOLDINGS INC.',
                'ReferenceNbr' => 'PV-2026-0009',
                'PostDate'     => Carbon::now()->subDays(2)->format('Y-m-d'),
                'Currency'     => 'PHP',
                'CheckNo'      => 'CHK000009',
                'APAccount'    => '2000',
                'APPayment'    => 60000.00,
                'CHAccount'    => '1100',
                'CHPayment'    => 60000.00,
                'BLAmount'     => 60000.00,
                'Purpose'      => 'PAYMENT FOR WAREHOUSE RENTAL',
                'Name'         => 'SM PRIME HOLDINGS INC.',
                'Company'      => 'ROPALI CORPORATION',
                'Type'         => 'CHECK',
                'Total'        => 60000.00,
                'IsPrint'      => 0,
                            ],
            [
                'Vendor'       => 'V000010',
                'VendorName'   => 'JOLLIBEE FOODS CORPORATION',
                'ReferenceNbr' => 'PV-2026-0010',
                'PostDate'     => Carbon::now()->subDays(1)->format('Y-m-d'),
                'Currency'     => 'PHP',
                'CheckNo'      => 'CHK000010',
                'APAccount'    => '2000',
                'APPayment'    => 18000.00,
                'CHAccount'    => '1100',
                'CHPayment'    => 18000.00,
                'BLAmount'     => 18000.00,
                'Purpose'      => 'PAYMENT FOR CATERING SERVICES - COMPANY EVENT',
                'Name'         => 'JOLLIBEE FOODS CORPORATION',
                'Company'      => 'MOTORALI CORPORATION',
                'Type'         => 'CHECK',
                'Total'        => 18000.00,
                'IsPrint'      => 0,
                            ],
        ]);
    }
}
